### ISSUE TITLE
[timerMgr.js] doesn't seem to work correctly when handling timers for multiple keys

### ISSUE THREAD

**Issue by tavalin** [rkoshak/openhab-rules-tools#55] opened 2021-01-19 15:04 UTC
I've written the following JS rule so far:

```
triggers:
  - id: "1"
    configuration:
      groupName: gLastSeen
    type: core.GroupStateChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/javascript
      script: >+
        this.OPENHAB_CONF = (this.OPENHAB_CONF === undefined) ?
        java.lang.System.getenv("OPENHAB_CONF") : this.OPENHAB_CONF;

        load(OPENHAB_CONF+'/automation/lib/javascript/community/timerMgr.js');

        var Log = Java.type("org.openhab.core.model.script.actions.Log");


        // Only create a new manager if one doesn't already exist or else it will be wiped out each time the rule runs

        this.tm = (this.tm === undefined) ? new TimerMgr() : this.tm;

        var itemName = event.itemName


        var update_interval = "10s"

        Log.logInfo("Test", "Timer created for " + itemName + " with timeout of " + update_interval)

        this.tm.check(itemName,
                              update_interval,
                              function() { Log.logInfo("Test", itemName + " timermgr.js timer expired!"); },
                              true);

    type: script.ScriptAction

```

and get output as follows:

```
==> /logs/events.log <==

2021-01-19 14:58:09.498 [INFO ] [openhab.event.RuleUpdatedEvent      ] - Rule '6abe733799' has been updated.
2021-01-19 14:58:12.311 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'KitchenLights_LastSeen' changed from 2021-01-19T14:57:24.000+0000 to 2021-01-19T14:58:12.000+0000
==> /logs/openhab.log <==

2021-01-19 14:58:13.155 [INFO ] [org.openhab.core.model.script.Test  ] - Timer created for KitchenLights_LastSeen with timeout of 10s
==> /logs/events.log <==
2021-01-19 14:58:13.529 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'MasterBedroom_EnvironmentSensor_LastSeen' changed from 2021-01-19T14:41:22.000+0000 to 2021-01-19T14:58:13.000+0000
2021-01-19 14:58:13.535 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'MasterBedroom_Pressure' changed from 977.0 hPa to 977.3 hPa
2021-01-19 14:58:13.539 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'MasterBedroom_Humidity' changed from 50.54 to 50.46
2021-01-19 14:58:13.543 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'MasterBedroom_Temperature' changed from 19.93 °C to 19.82 °C
==> /logs/openhab.log <==
2021-01-19 14:58:13.596 [INFO ] [org.openhab.core.model.script.Test  ] - Timer created for MasterBedroom_EnvironmentSensor_LastSeen with timeout of 10s
2021-01-19 14:58:23.484 [INFO ] [org.openhab.core.model.script.Test  ] - MasterBedroom_EnvironmentSensor_LastSeen timermgr.js timer expired!
2021-01-19 14:58:23.651 [INFO ] [org.openhab.core.model.script.Test  ] - MasterBedroom_EnvironmentSensor_LastSeen timermgr.js timer expired!
```

The problem is that if you look at the last two lines, the output message should reference `MasterBedroom_EnvironmentSensor_LastSeen` and `KitchenLights_LastSeen` but it seems like the function supplied for the `MasterBedroom_EnvironmentSensor_LastSeen` has overwrote the function for the `KitchenLights_LastSeen` where the logging statement should reference the `KitchenLights_LastSeen`

Edit: Here's another set of logs with debugging enabled for the library:

```
==> /logs/events.log <==

2021-01-19 15:16:31.498 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'MasterBedroom_CeilingLight_PowerState' received command ON

2021-01-19 15:16:31.506 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'MasterBedroom_CeilingLight_PowerState' predicted to become ON

2021-01-19 15:16:31.513 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'MasterBedroom_CeilingLight_PowerState' changed from OFF to ON

2021-01-19 15:16:31.588 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'MasterBedroom_CeilingLight_LastSeen' changed from 2021-01-19T14:38:02.000+0000 to 2021-01-19T15:16:31.000+0000

==> /logs/openhab.log <==

2021-01-19 15:16:31.593 [INFO ] [org.openhab.core.model.script.Test  ] - Timer created for MasterBedroom_CeilingLight_LastSeen with timeout of 10s

2021-01-19 15:16:31.601 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Timer manager check called

==> /logs/events.log <==

2021-01-19 15:16:31.602 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'MasterBedroom_CeilingLight_Dimmer' changed from 0 to 100

==> /logs/openhab.log <==

2021-01-19 15:16:31.605 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Timer to be set for 2021-01-19T15:16:41.605085Z[Europe/London]

2021-01-19 15:16:31.606 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Creating timer for MasterBedroom_CeilingLight_LastSeen

2021-01-19 15:16:31.614 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Timer created for MasterBedroom_CeilingLight_LastSeen

==> /logs/events.log <==

2021-01-19 15:16:32.197 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'SecondBedroom_CeilingLight_PowerState' received command ON

2021-01-19 15:16:32.213 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'SecondBedroom_CeilingLight_PowerState' predicted to become ON

2021-01-19 15:16:32.226 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'SecondBedroom_CeilingLight_PowerState' changed from OFF to ON

2021-01-19 15:16:32.328 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'SecondBedroom_CeilingLight_LastSeen' changed from 2021-01-19T14:38:03.000+0000 to 2021-01-19T15:16:32.000+0000

==> /logs/openhab.log <==

2021-01-19 15:16:32.331 [INFO ] [org.openhab.core.model.script.Test  ] - Timer created for SecondBedroom_CeilingLight_LastSeen with timeout of 10s

2021-01-19 15:16:32.333 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Timer manager check called

==> /logs/events.log <==

2021-01-19 15:16:32.333 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'SecondBedroom_CeilingLight_Dimmer' changed from 0 to 100

==> /logs/openhab.log <==

2021-01-19 15:16:32.336 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Timer to be set for 2021-01-19T15:16:42.336358Z[Europe/London]

2021-01-19 15:16:32.337 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Creating timer for SecondBedroom_CeilingLight_LastSeen

2021-01-19 15:16:32.340 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Timer created for SecondBedroom_CeilingLight_LastSeen

==> /logs/events.log <==

2021-01-19 15:16:32.343 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'SecondBedroom_CeilingLight_LinkQuality' changed from 99.0 to 126.0

==> /logs/openhab.log <==

2021-01-19 15:16:36.581 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Timer expired for KitchenLights_LastSeen

2021-01-19 15:16:36.583 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Calling expired function function() { Log.logInfo("Test", itemName + " timermgr.js timer expired!"); }

2021-01-19 15:16:36.585 [INFO ] [org.openhab.core.model.script.Test  ] - SecondBedroom_CeilingLight_LastSeen timermgr.js timer expired!

2021-01-19 15:16:36.586 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Deleting the expired timer

2021-01-19 15:16:41.605 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Timer expired for MasterBedroom_CeilingLight_LastSeen

2021-01-19 15:16:41.607 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Calling expired function function() { Log.logInfo("Test", itemName + " timermgr.js timer expired!"); }

2021-01-19 15:16:41.608 [INFO ] [org.openhab.core.model.script.Test  ] - SecondBedroom_CeilingLight_LastSeen timermgr.js timer expired!

2021-01-19 15:16:41.609 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Deleting the expired timer

2021-01-19 15:16:42.337 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Timer expired for SecondBedroom_CeilingLight_LastSeen

2021-01-19 15:16:42.338 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Calling expired function function() { Log.logInfo("Test", itemName + " timermgr.js timer expired!"); }

2021-01-19 15:16:42.340 [INFO ] [org.openhab.core.model.script.Test  ] - SecondBedroom_CeilingLight_LastSeen timermgr.js timer expired!

2021-01-19 15:16:42.340 [DEBUG] [.openhab.model.script.Rules.TimerMgr] - Deleting the expired timer
```

**Comment by rkoshak** [comment] 2021-01-20 18:10
This is a generic JavaScript (and Python for others who stumble upon this problem) issue. What is happening is the first time the rule runs itemName gets set to one value. A timer gets created. Later on itemName gets set to a different value. The problem is itemName is pointing to the same place in memory so when the timer finally does run, itemName holds the value from the most recent run of the rule instead of what itemName was set to when the Timer was created.

The way to fix this problem when it occurs is to use a function generator instead of a plain old anonymous function. 

```javascript
var functionGenerator = function(itemName) {
    return function() { Log.logInfo("Test", itemName + " timermgr.js timer expired!"); };
};

this.tm.check(itemName,
                      update_interval,
                      functionGenerator(itemName),
                      true);
```

When you call the function a itemName gets fixed in that context and won't become overwritten in subsequent runs of the script.

This is a problem whether or not you are using TimerMgr.

**Closed by rkoshak** 2021-01-20 18:10 UTC

**Comment by tavalin** [comment] 2021-01-21 11:50
Thanks @rkoshak, that seems to work.  Coincidentally I don't recall having this issue with your python version of timerMgr.  

Is it possible to adapt the timerMgr.js so that it automatically wraps the supplied function in a "generator"? Excuse my lack of JS expertise 😄

**Comment by rkoshak** [comment] 2021-01-25 23:59
I've been trying to figure out a way to do that but have not come up with anything that would work in a generic way. This might be just one of those things people will just have to get used to doing.

I *have* seen a similar problem in Python, though it's mostly when iterating over a list. I've not explored UI rules with Python so it might be an issue that is more pronounced when working through the UI.
